### ISSUE TITLE
Kernel panic on last commit

### ISSUE THREAD

**Issue by Linaro1985** [vschagen/mtk-eip93#17] opened 2021-10-28 09:40 UTC
Hi @vschagen. Thanks for your's work!

I got a kernel panic using this command:
openssl speed -elapsed -evp aes-256-cbc

after update to https://github.com/vschagen/mtk-eip93/commit/84291b049097651fa6918bbc1c420161994039ef , this commit https://github.com/vschagen/mtk-eip93/commit/5bd58b26e56b958232c1531b7ac59d468b1173f8 works fine.

By the way I have a question related to small blocks for aes and des. Fallback was available for small blocks on your's old implementation. Did you remove this because it doesn't make sense?

**Comment by vschagen** [comment] 2021-10-28 14:04
Thank you for the feedback. It is fixed again.

Yes, for the moment fallback is removed to try and get the code merged upstream into the main linux kernel.
For userspace crypto small block will always be slower than software. I have an experimental version where I don't even user interrupts, but poll the hardware directly after starting the DMA action. This improves openssl benchmarks but is more CPU intensive. The downside to this is that it is "blocking" which is not a problem for most userspace applications, but kernel space will suffer because of this (think: DM-crypt or IPSec). OpenVPN (with OpenSSL dev/crypto) will improve a little using this approach but with normal MTU sizes it will give minimal performance improvement.

When this is accepted into the mainline kernel I will start looking into a hardware specific userspace engine (either openssl or wolfssl). This would not work together with the standard crypto kernel API but should improve userspace performance.

Closing this as the kernel panic caused by the commit has been fixed.

**Closed as completed by vschagen** 2021-10-28 14:04 UTC
